config/routes.rb
Rails.application.routes.draw do
  root "sounds#index"
  resources :sounds
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/sound.rb
class Sound < ApplicationRecord
    has_one_attached :file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sounds_controller.rb
class SoundsController < ApplicationController
  before_action :set_sound, only: %i[ show edit update destroy ]

  # GET /sounds or /sounds.json
  def index
    @sounds = Sound.all
  end

  # GET /sounds/1 or /sounds/1.json
  def show
  end

  # GET /sounds/new
  def new
    @sound = Sound.new
  end

  # GET /sounds/1/edit
  def edit
  end

  # POST /sounds or /sounds.json
  def create
    @sound = Sound.new(sound_params)

    respond_to do |format|
      if @sound.save
        format.html { redirect_to sound_url(@sound), notice: "Sound was successfully created." }
        format.json { render :show, status: :created, location: @sound }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sounds/1 or /sounds/1.json
  def update
    respond_to do |format|
      if @sound.update(sound_params)
        format.html { redirect_to sound_url(@sound), notice: "Sound was successfully updated." }
        format.json { render :show, status: :ok, location: @sound }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @sound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sounds/1 or /sounds/1.json
  def destroy
    @sound.destroy

    respond_to do |format|
      format.html { redirect_to sounds_url, notice: "Sound was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sound
      @sound = Sound.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def sound_params
      params.require(:sound).permit(:name, :description, :file)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sounds_helper.rb
module SoundsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sounds/_form.html.erb
<%= form_with(model: sound) do |form| %>
  <% if sound.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(sound.errors.count, "error") %> prohibited this sound from being saved:</h2>
      <ul>
        <% sound.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.label :file, style: "display: block" %>
    <%= form.file_field :file %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sounds/_sound.html.erb
<div id="<%= dom_id sound %>">
  <p>
    <strong>Name:</strong>
    <%= sound.name %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= sound.description %>
  </p>
  <p>
    <strong>File:</strong>
    <%= audio_tag(url_for(sound.file), controls: true, id: "wave_audio", data: {
    controller: "wave",
    wave_url: url_for(sound.file)
  }) %>
  </p>
  <canvas id="wave_canvas"></canvas>
</div>

app/views/sounds/edit.html.erb
<h1>Editing sound</h1>

<%= render "form", sound: @sound %>

<br>

<div>
  <%= link_to "Show this sound", @sound %> |
  <%= link_to "Back to sounds", sounds_path %>
</div>

app/views/sounds/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Sounds</h1>

<div id="sounds">
  <% @sounds.each do |sound| %>
    <%= render sound %>
    <p>
      <%= link_to "Show this sound", sound %>
    </p>
  <% end %>
</div>

<%= link_to "New sound", new_sound_path %>

app/views/sounds/new.html.erb
<h1>New sound</h1>

<%= render "form", sound: @sound %>

<br>

<div>
  <%= link_to "Back to sounds", sounds_path %>
</div>

app/views/sounds/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @sound %>

<div>
  <%= link_to "Edit this sound", edit_sound_path(@sound) %> |
  <%= link_to "Back to sounds", sounds_path %>

  <%= button_to "Destroy this sound", @sound, method: :delete %>
</div>